# 网站设置
title: My Blog
description: A beautiful blog powered by Jekyll
baseurl: ""
url: ""

# 主题设置
theme: minima

# 构建设置
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# 导航菜单
header_pages:
  - about.md
  - archive.md
  - categories.md

# 评论系统设置
comments:
  provider: giscus

# 分页设置
paginate: 10
paginate_path: "/page:num/"

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
